= Politicization in Science

== Brief: Science is an important process of developing and systematizing objective knowledge about reality. Does politicization in science happen these days, and what impact does it have?

Science is an important process of developing and systematizing objective knowledge about reality. There is also politicization in science as a way for politicians to influence people's minds with scientific knowledge. Many states deny the presence of politicization in science, but the problem exists.

Social sciences such as philosophy, sociology, jurisprudence, and psychology are connected with the process of political decision-making. If the problem of politicization of the above-mentioned sciences raises almost no questions, there are discussions about the politicization of history. It is believed that politicization in the field of historical science is inevitable, as it begins at the individual level. The views of a specialist historian about the current social situation are transferred to historical politics and not only that is why terms such as "historians-conservatives", " historians-marxists", and "liberal historians" appear. From this follows a biased presentation of information in textbooks. The problem of the politicization of academic disciplines is also related to the politicization of educational institutions. This process is understood as the open expression, demonstration of their political position, and sympathies by people who have authority and influence. Universities and schools are considered to be apolitical, and such manifestations contradict not only the law but also the educational principle of "unbiased learning.

Also important activities in science sometimes do not reflect an objective scientific view. The Nobel Prize is a prime example. The top five countries with the highest number of Nobel laureates are the United States, the United Kingdom, Germany, France, and Sweden. These countries have an enormous influence on the world political arena. Achievements of scientists from post-Soviet countries or those with little influence (African countries, some Asian countries) often remain underestimated. Politics also has a negative impact on scientific progress through repression and downgrading of certain disciplines. The case of Liu Xiaobo, Nobel Peace Prize laureate for his long and non-violent struggle for basic human rights in China, is notable. He was sentenced to 11 years in prison for undermining the state system. The Chinese media reported nothing about his Nobel Prize and prevented him from receiving it through family and friends. The Danish theoretical physicist Niels Bohr is another example of a scientist being pinched by the political regime. As an expert in atomic physics, he was invited by Nazi scientists to develop an atomic bomb for Germany. But he refused and, fleeing occupied Denmark, he called for a complete ban on nuclear weapons and strict international control over them. The very fact that atomic energy was used for military purposes is evidence of the politicization of scientific knowledge.

Thus, such an objective and independent field as science are subject to politicization and subjectivization. The strengthened influence of politics is not always good for the development of scientific ideas if they are not closely related to their subject area. In today's society, political awareness is an integral part of everyone's life. Increasing public literacy generates people interested in politics, including potential investors in science. Financial support is allocated to promising areas, expanding opportunities, and the field for more high-quality research. Thus, the politicization of science is an ambiguous phenomenon, viewed differently depending on time and social standing.

