= Research paper on "Gender stereotypes among students"

== Brief: The opinion of more than 900 students of belarusian universities was considered in the research work. Important gender problems of the society were raised, analyzed and evaluated with the subsequent conclusions.

== Thesis:

Based on the results of the survey, one can observe a number of very interesting results.

First, in all questions requiring a negative or positive answer, the voices of female and male respondents differed significantly in one way or another. Take the most illustrative example: "Do you think that fighting for women's independence from men these days is useless and even harmful to women themselves?" Less than 20 percent of women and more than 50 percent of men agreed with this statement. Moreover, men are more convinced that women receive equal wages with them, and also cannot be effective managers due to their emotionalism. Modern sociological and scientific studies, however, do not confirm the ineffectiveness of women managers, as these are personal characteristics, not gender. Also, women's salaries are 27.3\% lower than men's (Belstat data for 2019). Thus, these stereotypes are quite common among male respondents.

Also noteworthy is the question about the prohibition of women in certain professions, the opinions on which are approximately the same. Women and men were relatively equally against this ban or for the purpose of preserving reproductive or physiological health. These results show the stereotype that men tend to take health risks, while women should be in less risky jobs, despite their wishes.

Another controversial question about the right to carry a baby showed that 57% of the male respondents considered this decision to be jointly made, while 47% of the female respondents thought it should be a woman's decision and only 32% were in agreement that this decision is acceptable to make jointly. Also respondents indicated in the "Other" field options where the decision can be made by both partners, but in case of divergence of their interests the last word belongs to the woman, because it is an immediate danger to her body.

The questions about the qualities peculiar to men and women included deliberately stereotypical qualities with a few non-standard features (for men it was "Compassion" and "Caring", for women it was "Intelligence"). Most respondents replied "Self-mastery" (65,4%), "Courage" (53,7%), "Pragmatism" (42,4%), and for female qualities - "Sensitivity" (70,7%), "Caring" (59,4%), "Empathy" (33,5%). The qualities described above are common opinions about "ideal" men and women. But there were interviewees who wrote in the column "Other" about the uniqueness of personal characteristics and their non-attachment to gender.

In conclusion, we can say that these stereotypes do exist among the younger generation, especially among men. Nevertheless, many different answers to the questions about the fetus and its rights and restrictions on women's labor, as well as a large proportion of women's answers against stereotypes showed the non-conformist thinking of this part of society. It may be connected with the pro-feminist movement and the active emancipation of women, which began in the West and has gradually come to us.
