= The impact of the World War II on the culture of the BSSR in the first postwar decade

== Brief: The article describes the difficulties and achievements of the development of Belarusian culture in the first postwar decade.

== Article:

The Belarusian people will remember the Great Patriotic War for a long time with great pity and pain. She turned out to be a red spot on our history. People, both civilians, and soldiers defended our homeland at that time. Every third inhabitant died. Most businesses were looted, most cities ruined, and railroads destroyed. Agriculture was in a catastrophic situation. All this needed to be restored. 


After the war, the political system did not lose its one-party rule, a cult of personality, and suppression of dissent, it was quite rigid. Accordingly, during this period in the culture of the BSSR socialist realism reigned (a trend in art, which was characterized by the reflection of only the positive aspects of Soviet reality). The principle of partisanship has prevailed in Belarusian literature - it is an unspoken rule according to which patriotism or its ideas were praised in works of art. Cultural figures objectionable to the authorities, who were already few in number, were repressed ... 


The most understandable and accessible branch of culture is literature. The main topic was the military. M. Lynkou's work "Memorable Days" is published, in which K. Zaslonau, a historical figure, one of the well-known figures of the underground resistance, appears as one of the main characters. Kolas is working fruitfully at this time. The writer has completed work on the poem "Fisherman's House" and the trilogy "At the Crossroads". K. Chorny's novel The Milky Way is published, which shows the fate of the people during the war. Famous poets of that time were M. Tank, P. Panchenko, P. Brovka, and A. Kuleshov. Each of these people deserves special attention, but speaking of the war, I can not fail to mention the "Ballad of the Four Hostages", which, in my opinion, is the strongest description of the feat of the liberators of our country. After the war, theatrical and musical life was restored. Evacuated theaters are returning home. In 1946 the film studio "Belarusfilm" began its activity. The films "Green Lights", "Mikolka-Locomotive", and "The Clock Stopped at Midnight" were shot. 


Painting developed in accordance with socialist realism. A striking example is V. Volkov’s painting “Minsk. July 3, 1944". Sculpture was developed, and images of Heroes of the Soviet Union, guerrillas, and soldiers were created. In 1954, an obelisk monument to Soviet soldiers and guerrillas killed in the fight against fascism was built in Victory Square (Z. Azgur). Architecturally, Minsk was developed according to the master plan approved by the BSSR authorities in 1946. A new center was created with the main highway, which opened to the square, at the moment this place is called Independence Avenue. Projects on construction and arrangement of the avenue were actively implemented. 


In general, after the war, the capital was in a difficult situation, so much effort was made to rebuild and reconstruct the destroyed buildings. Thus, we can say that in the postwar period, the culture of our country did not stand still, but continued its development, inspiring people to rebuild the homeland and leaving a valuable legacy for posterity.
