= The Phenomenon of Zwischenism

The problem of the difficulty of resolving contradictions has existed in people's minds for many years. People often experience difficulty in making choices, and confusion can arise not only in the mind of an individual, but also in society as a whole. This phenomenon was given the name of zwischenism; it is an opposition to stability. According to Y. A. Kharin this term denotes the "inter-being" of a person in a state of crisis of spiritual values, alternative choices, uncertainty and uncertainty, the predominance of spontaneity in human actions associated with value and ideological disorientation.


In the context of the development of human thought and the accompanying cycle of information, there can be difficulties in eliminating this problem, since there is a diversity of opinions in society and a variation of levels of understanding of everything going on around it. 


Modern man has to surpass his predecessors in his ability to assimilate information and process it. Every day there are more and more technologies and various scientific developments that require our attention and ability to deal with newly discovered material. This simultaneously complicates and simplifies the decision-making process. On the one hand, there are techniques to increase the efficiency of perception of reality and the reliability of the information obtained, eliminating the factor of uncertainty. On the other hand, there is an even greater amount of information requiring a detailed analysis with subsequent conclusions. It turns out that the more a person asks a question, the more contradictions and ambiguities arise in the process of trying to get a reasonable answer. In the context of the modern world, in which many different ideologies and opinions coexist, it can be very difficult to determine the correct and most effective solution. 

It would be much easier if this problem could be solved by objectively comparing incoming information using an automated system for comparing information sorted from databases. It would be more effective to enhance the ability of artificial intelligence to analyze information and arrange it according to certain criteria. More objective would be a cold-blooded response from a system that does not take into account a person's subjective attitudes toward a given question.


However, not all questions pertaining to human existence can be solved by a highly intelligent system, since to understand and resolve existential-psychological zwischenism, one needs the experience of resolving a similar problem from individuals who have already faced it, and also the reflexive approach of the individual who has faced it because often many answers to existential questions that worry us lie within us. 


The state of being "inter-being" is produced by the individual himself. Thus, zwischenism is a fairly common problem today, with a rather simple solution for the practical part and a rather complicated one for the spiritual part. Despite the fact that we associate this age with a great development of mathematical logic in people, and, as a consequence, improvement of structuring of knowledge in a person's head, it is not possible to destroy zwischenism, at least partially. However, it is not necessary to eradicate zwischenism, because it is uncertainty and human unpredictability that makes everyone around not robots, but humans.
